/*
 * MOTORDRIVR_INT.h
 *
 *  Created on: Nov 26, 2018
 *      Author: Abdallah
 */

#ifndef MOTOR_DRIVER_DRIVER_MOTORDRIVER_INT_H_
#define MOTOR_DRIVER_DRIVER_MOTORDRIVER_INT_H_


typedef enum MOTORDRIVER_enuState
		{
	    MOTORDRIVER_NORMALSTATE=0,
		}MOTORDRIVER_enuState;
void MOTORDRIVER_INIT();
u8 MOTORDRIVER_MOVE_FORWARD();
u8 MOTORDRIVER_ROTATE_RIGHT();
u8 MOTORDRIVER_ROTATE_LEFT();
u8 MOTORDRIVER_MOVE_BACKWARD();
u8 STOP();


#endif /* MOTOR_DRIVER_DRIVER_MOTORDRIVER_INT_H_ */
